Tutorial on fast, named capture regular expressions in R

R >= 2.14 supports named capture regular expressions via C code that
interfaces the fast Perl-Compatible Regular Expressions (PCRE)
library. In this 60 minute tutorial I will explain how to use regular
expressions to extract data from several different kinds of text
files.

** Overview, 15 minutes

Base R provides =regexpr= and =gregexpr= functions, which use PCRE
when given the perl=TRUE argument. The first argument is a single
regular expression (character vector of length 1), and the second
argument is a character vector of strings to parse. However their
output is a bunch of integers so I made some interface functions that
return character data.

| base function | my function        |
|---------------+--------------------|
| regexpr       | str_match_perl     |
| gregexpr      | str_match_all_perl |

** Some examples, 15 minutes

| R code          | functions                                |
|-----------------+------------------------------------------|
| [[file:chr.pos.R]]  | str_match_perl, str_match_all_perl, gsub |
| [[file:qsub-out.R]] | str_match_perl                           |

** Exercises 
