---
title: "Extracting tabular data from text using regular expressions"
author: |
   | Toby Dylan Hocking^1^ 
   |
   | 1. Northern Arizona University, Flagstaff, USA
output: html_document
---

**Keywords**: text, tabular, data, manipulation, regex, pattern, regular, expression.

## Goals/Aims/Learning objectives

Following the course participants will be able to:

* recognize structure in non-tabular textual data files (html, logs, genomics, etc) that can be matched via regex.
* create regular expressions using basic and advanced features (character classes, alternation, multi-line patterns, etc).
* use (named) capture groups to extract data tables with numeric columns from loosely structured textual data.
* use rex/namedCapture packages to create readable and maintainable R code that generates regular expressions.
* create R applications that acccept user-defined regex patterns, and resist denial-of-service attacks, by using polynomial time regex libraries (TRE/RE2).
 
## Justification

Regular expressions are extremely powerful tools for manipulating
non-tabular textual data. For many tasks (visualization, fitting
machine learning models, etc), tables of numbers must be extracted
from such data before processing by other R functions. One line of
R/regex code can often be used to compute the same result as many
lines of non-regex R code. Furthermore, using regex for text
manipulation often results in much faster computation times. Learning
regex thus makes a useR much more productive.

## Brief description of Tutorial
 
Regular expressions have been available for many years in R. In recent
years there have been several new packages for regex (namedCapture,
rex, stringr, stringi, tidyr, rematch2, re2r). This tutorial will give
an overview of these packages, highlighting their similarities,
differences, and individual strengths. It contains interactive
exercises with real-world examples (web scraping, genomics,
supercomputing, log parsing).

## Detailed outline of tutorial content

We have created the following reference table for this tutorial, which
will be used to explain the similarities and differences between the regex
R packages that we will discuss.

  Package        First match                 All matches                library    subject   pattern        outputs       named   types
  -------------- --------------------------- -------------------------- ---------- --------- -------------- ------------- ------- -------
  base           `regexpr`                   `gregexpr`                 PCRE/TRE   chr       chr            mat/list      yes     no
  utils          `str_capture`               NA                         PCRE/TRE   chr       chr            df            no      some
  namedCapture   `str_match_named`           `str_match_all_named`      PCRE       chr       chr            mat/df/list   yes     any
  namedCapture   `str_match_variable`        `str_match_all_variable`   PCRE       chr       verbose        mat/df/list   yes     any
  namedCapture   `df_match_variable`         NA                         PCRE       df/dt     verbose        df/dt         yes     any
  rex            `re_matches(global=FALSE)`  `re_matches(global=TRUE)`  PCRE       chr       verbose        df            yes     no
  stringr        `str_match`                 `str_match_all`            ICU        chr       chr            mat/list      no      no
  stringi        `stri_match`                `stri_match_all`           ICU        chr       chr            mat/list      no      no
  tidyr          `extract`                   NA                         ICU        df/dt     chr            df/dt         no      some
  rematch2       `re_match`                  `re_match_all`             PCRE/TRE   chr       chr            tibble        yes     no
  re2r           `re2_match`                 `re2_match_all`            RE2        chr       chr/compiled   df/list       yes     no

The columns can be interpreted as follows:

* First match is a function that extracts the first regex match found in the subjects.
* All matches is a function that extracts each regex match found in the subjects.
* library is the underlying C code used for regex parsing. PCRE and ICU are exponential time complexity, whereas RE2/TRE are polynomial time complexity (which can be used to avoid denial-of-service attacks in R applications which allow users to input a regex).
* subject/pattern/outputs shows the supported data types.
* named is for named capture group support.
* types is for built-in type conversion (useful for extracting numeric
  data from text).
  
As explained below, the tutorial is divided into two 90 minute
talks. The first half gives an overview of the relative advantages of
the different regex packages in R, and the second goes in depth about
how to use regex to parse several types of files (web pages, logs,
genomic data).

### First half of tutorial: overview of regex and R packages

#### Intro to regex, 30 minutes

* Example: converting chrom position strings "chr1:100-200" to three-column data table.
* Use of ".*?" versus "[^:]*:" patterns.
* Capturing groups without names -- ICU, stringr, stringi, tidyr packages.
* Named capture groups -- PCRE, namedCapture, rex, rematch2 packages.
* Application/exercise: sort positions by chrom number then
  start/end. Tricky since some chrom names have letters and suffixes,
  e.g. chr1, chr2, chr17, chr17_ctg5_hap1, chrY.

#### Maintainable R/regex code 20 minutes

* namedCapture and rex packages.
* rex log parsing example.

#### Polynomial time regex, 20 minutes

* Base R (TRE), re2r package (RE2).
* Examples from StackOverflow ReDoS, Java classname,
  etc. http://qinwenfeng.com/re2r_doc/benchmark.html

#### Tidy regex functions which input/output data frame, 20 minutes

* tidyr::extract and namedCapture::df_match_variable.
* Example: parsing sacct output.
* Short versus long syntax.

### Second half of tutorial: regex for several specific examples
 
#### Web scraping, 30 minutes

* Example: parsing data from R-Forge web pages.
* Plot number of R-Forge projects over time.
* Plot users per project.

#### Parsing qsub logs, 30 minutes

* Examples: https://github.com/tdhock/regex-tutorial/tree/master/qsub-out
* Use system/grep to get only Resources lines, parse with `str_match_variable`.
* Extract all limits/resources using `str_match_all_variable`, subject
  is character vector with one element per line of one file.
* Extract two time specs using `str_match_variable`, show re-use of
  sub-patterns, subject
  character vector is one element per file.

#### Parsing trackDb files, 30 minutes

* https://raw.githubusercontent.com/tdhock/regex-tutorial/master/trackDb.txt
* https://raw.githubusercontent.com/tdhock/regex-tutorial/master/trackDb2.txt
* Contrast strsplit + single-line regex with multi-line regex.

## Pre-requisite background knowledge and packages

Only a basic knowledge of R is required, so even new useRs should be
able to benefit from this tutorial.

We will provide a rendered Rmd to tutorial attendees for reference. At the top it
will have a code chunk which will install all required packages.

## Potential attendees

This tutorial should be useful for both new and power useRs, because
it explains both the basics of regex, as well as new/advanced features
of some packages (namedCapture, rex, re2r). 

## Instructor Biographies

Toby Dylan Hocking (toby.hocking@r-project.org,
https://github.com/tdhock) is an Assistant Professor in the School of
Informatics, Computing, and Cyber Systems at Northern Arizona
University. His main research project concerns new machine learning
models for genomic data, which often requires pre-processing using
regular expressions.

He contributed the code in
https://svn.r-project.org/R/trunk/src/main/grep.c which implements
named capture regular expression support for R. It was merged into
base R in 2011
https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=14518, and has
been included with every copy of R since version 2.14. He is the
author of the namedCapture package which provides a user-friendly
interface for extracting tabular data from loosely structured text
using regular expressions.

He has implemented several R graphics packages, including directlabels
(won best student poster at useR2011) and animint (presented in a
JSM2015 invited session and a useR2016 tutorial). He has also
presented a useR2017 tutorial on Supervised Changepoint Detection.

