---
title: "Regular expressions for data parsing, reshaping, and visualization"
author: |
   | Toby Dylan Hocking^1^ 
   |
   | 1. Northern Arizona University, Flagstaff, USA
output: html_document
---

**Keywords**: text, tabular, data, manipulation, parsing, reshape, regex, pattern, regular, expression, visualization.

Submissions must be in English and include/indicate:

    Language in which the tutorial can be taught
    The title of the tutorial
    A brief biography of the instructors
    The broad topic it covers
    Abstract (250 words max)
    Intended audience and prerequisites
    A brief outline of the tutorial
    If it exists, a link to the tutorial materials and/or webpage

Review Criteria

Our program committee will carefully evaluate each submission’s overall quality, research scope, and potential appeal to the R community, and check its technical content and pedagogical approach.

https://user2022.r-project.org/participate/tutorial-access/

https://redcap.vanderbilt.edu/surveys/?s=DJX9LXFYKDW8HALT 

 useR! 2022 has virtual and in-person components. Which type of tutorial are you proposing?
virtual (Saturday, 18 June 2022)
in-person (Monday, 20 June 2022) Nashville, Vanderbilt.
either virtual or in-person, at the discretion of the organizing committee
reset
	

useR! 2022 tutorials are organized into morning and afternoon sessions. 
  	Virtual (Saturday, 18 June 2022) 	In-person (Monday, 20 June 2022)
Morning 	6:30 - 10:00 CDT 	9:00 - 12:30 CDT
Afternoon 	16:00 - 19:30 CDT 	14:00 - 17:30 CDT

 

What is your preference for the timing of your tutorial?
no preference, I can present during either the morning or afternoon sessions
morning session
afternoon session
reset
	
Tutorials may be presented in English, French, or Spanish. Will your tutorial be in English, French, or Spanish?
* must provide value
English
French
Spanish
reset
	
Including breaks, how long will your tutorial be?
* must provide value
1.5 hours 	2.5 hours 	3.5 hours
	
Change the slider above to set a response 	
reset
	
How many participants can you accommodate in your tutorial?
10
20
30
40
50
unlimited
reset
	
What is the title of your tutorial?
* must provide value
	
Name of corresponding author/organizer
* must provide value
	
Email address of corresponding author/organizer
* must provide value
	
Please provide an introduction to each instructor (2-3 sentences).

For example:

Jon Arbuckle - Jon Arbuckle is a data scientist with interest in statistics and machine learning education, and experience in machine learning research. His work involves application of machine learning methods in the shipping industry.
* must provide value
Expand 
	
Please select a primary topic area for your tutorial.
* must provide value
	
Please provide 3-5 keywords that identify the focus of your tutorial.

For example:

clinical trials, reporting, reproducibility
* must provide value
	
Abstract. Please provide a brief summary of your tutorial (up to 250 words).
* must provide value
250 words remaining
Expand 
	
Please describe the intended audience for your tutorial. For example, is your tutorial primarily for new users of R? Is it for R package developers? If there are prerequisites or requirements for participants, please list them here.
* must provide value
Expand 
	
Please provide a brief outline of the tutorial. Be sure to describe when and how students will actively engage with the material, including any hands-on examples, breakout sessions, or participant polling. If available, please include links to any instructional materials or relevant webpages.


## Goals/Aims/Learning objectives

Following the course participants will be able to:

* recognize structure in non-tabular text data files (html, logs,
  genomics, etc) that can be matched and parsed via regex.
* create regular expressions using basic and advanced matching
  features (character classes, alternation, multi-line patterns, etc).
* use a capturing regular expression to extract a data table from
  non-tabular text data.
* understand the basic differences in terms of functionality between
  the regex libraries available in R (C libraries PCRE, TRE, ICU, RE2;
  R packages stringi and re2r).
* create readable and maintainable R code that generates regular
  expressions (R packages nc and rex).
* use regular expressions to specify columns in a wide-to-long data
  reshaping operation (R packages tidyr, data.table, nc).
 
## Justification

Regular expressions are extremely powerful tools for parsing
non-tabular text data, and for specifying columns in wide-to-long data
reshape operations. For many tasks (visualization, fitting machine
learning models, etc), tables of numbers must be extracted from such
data before processing by other R functions. One line of R/regex code
can often be used to compute the same result as many lines of
non-regex R code. Furthermore, using regex for text manipulation often
results in much faster computation times. Learning regex thus makes a
useR much more productive.

## Brief description of Tutorial
 
Regular expressions have been available for many years in R. In recent
years there have been several new packages which provide regex
functionality for data parsing and reshaping (stringi, re2r, rex,
tidyr, data.table, nc). This tutorial will give an overview of these
packages, highlighting their similarities, differences, and individual
strengths. It contains interactive exercises with real-world examples
(web scraping, genomics, supercomputing, log parsing).

## Detailed outline of tutorial content

We have written two research articles on this subject, which we will
draw from (TODO CITE R Journal papers). As explained below, the
tutorial is divided into two 90 minute talks. The first half goes in
depth about how to use regex to parse and visualize several types of
non-tabular text data files (web pages, logs, genomic data). The
second half continues discussion of several real data examples, and
gives an overview of some advanced features (wide-to-long data
reshaping, etc).

### First half of tutorial: overview of regex and R packages

#### Overview of regex packages, 30 minutes

* Running example: converting chrom position strings "chr1:100" to
  two-column data table.
* Base R functions: `strcapture`, `regexec`, `gregexec`.
* Plotting using `ggplot2` package.
* Comparison with functions from `stringi`, `rex`, `re2r`, `rematch2`
  packages.
* Advantages of functions from `nc` package.
* Mention time complexity of different C libraries, with examples from
  StackOverflow ReDoS, Java classname,
  etc. http://qinwenfeng.com/re2r_doc/benchmark.html
* Application/exercise: sort positions by chrom number then
  start/end. Tricky since some chrom names have letters and suffixes,
  e.g. `chr1, chr2, chr17, chr17_ctg5_hap1, chrY`.

#### Functions which parse character columns, 15 minutes

* Functions from `tidyr` package.
* `nc::capture_first_df`.
  
#### Web scraping, 15 minutes

* Example: parsing data from R-Forge web pages.
* Plot number of R-Forge projects over time.
* Plot users per project.

#### Parsing qsub logs, 15 minutes

* Examples: https://github.com/tdhock/regex-tutorial/tree/master/qsub-out
* Use system/grep to get only Resources lines, parse with `str_match_variable`.
* Extract all limits/resources using `str_match_all_variable`, subject
  is character vector with one element per line of one file.
* Extract two time specs using `str_match_variable`, show re-use of
  sub-patterns, subject
  character vector is one element per file.

#### Parsing trackDb files, 15 minutes

* https://raw.githubusercontent.com/tdhock/regex-tutorial/master/trackDb.txt
* https://raw.githubusercontent.com/tdhock/regex-tutorial/master/trackDb2.txt
* Contrast strsplit + single-line regex with multi-line regex.

### Second half of tutorial: regex for several specific examples
 
#### R-to-regex translators 20 minutes

* nc and rex packages.
* rex log parsing example.

#### Tidy regex functions which input/output data frame, 20 minutes

* `tidyr::extract` and `nc::capture_first_df`.
* Example: parsing sacct output.
* Short versus long syntax.

#### Wide-to-long data reshaping, TODO minutes

* `tidyr::pivot_longer`.
* data.table package: `melt`, `measure`.
* nc package: `capture_melt_single`, `capture_melt_multiple`.

## Pre-requisite background knowledge and packages

Only a basic knowledge of R is required, so even new useRs should be
able to benefit from this tutorial. 

We will provide a rendered Rmd to tutorial attendees for reference. At
the top it will have a code chunk which will install all required
packages.

## Potential attendees

This tutorial should be useful for both new and power useRs, because
it explains both the basics of regex, as well as new/advanced features
of some packages (for example nc, rex, tidyr, data.table). Both new
and advanced useRs will certainly appreciate our detailed presentation
of the similarities and differences between the various R packages
with regex functionality.

## Instructor Biographies

Toby Dylan Hocking (toby.hocking@r-project.org,
https://github.com/tdhock) is an Assistant Professor in the School of
Informatics, Computing, and Cyber Systems at Northern Arizona
University. His main research project concerns new machine learning
models for genomic data, which often require pre-processing using
regular expressions. He contributed the code in base R which
implements named capture regular expressions, as well as several other
improvements related to regular expressions in base R and the data.table
package. He is maintainer of the CRAN package nc for "named capture"
regular expressions. In previous conferences he has presented his
packages directlabels (won best student poster at useR2011) animint
(JSM2015 invited session and useR2016 tutorial on interactive
graphics), penaltyLearning (useR2017 tutorial on supervised
changepoint detection), and PeakSegDisk (useR2019 contributed talk).

