** Parsing nbib files

The MEDLINE nbib citation format looks like [[file:PMC3045577.nbib]],
#+begin_src
PMID- 21113027
OWN - NLM
STAT- MEDLINE
DCOM- 20110512
LR  - 20181113
IS  - 1362-4962 (Electronic)
IS  - 0305-1048 (Print)
IS  - 0305-1048 (Linking)
VI  - 39
IP  - 4
DP  - 2011 Mar
TI  - A manually curated ChIP-seq benchmark demonstrates room for improvement in current 
      peak-finder programs.
PG  - e25
...
#+end_src

Exercise: parse that file into key-value pairs using a regex.

** Parsing a web page to understand what each abbreviation means

The [[file:MEDLINE_Fields.html]] web page has a table which can be used to
understand what the key abbreviations mean,

#+begin_src
<tr>
<td><a href="#ab">Abstract</a></td>
<td><a href="#ab">(AB)</a></td>
</tr>
<tr style="background-color: #cccccc;">
<td><a href="#ci">Copyright Information</a></td>
<td>
<div><a href="#ci">(CI)</a></div>
</td>
</tr>
<tr>
<td><a href="#ad">Affiliation</a></td>
<td>
<div><a href="#ad">(AD)</a></div>
</td>
</tr>
#+end_src

Each entry is a row in the table, corresponding to a <tr> block in the
HTML code. Exercise: parse that web page to get a table of
abbreviations (for example AD) and descriptions (for example
Affiliation).

Exercise: join the two tables so you have a table with three columns,
Abbreviation, Description, Value.

** Parsing bib files

Another citation format has the extension bib, used by
bibtex/latex. Exercise: use a regex to parse
[[file:namedCapture-refs.bib]]. How many references are there of each
type? Are there any authors which are cited in multiple different
papers?
