library(data.table)
arg.dt <- fread(text="dt.fun	dt.arg.name	expected	in.base
[.data.table	x	simple	TRUE
[.data.table	i	simple	TRUE
[.data.table	j	simple	TRUE
[.data.table	by	simple	FALSE
[.data.table	keyby	minimal	FALSE
[.data.table	with	simple	FALSE
[.data.table	nomatch	minimal	FALSE
[.data.table	mult	abbrev	FALSE
[.data.table	roll	simple	FALSE
[.data.table	rollends	minimal	FALSE
[.data.table	which	simple	FALSE
[.data.table	.SDcols	minimal	FALSE
[.data.table	verbose	simple	FALSE
[.data.table	allow.cartesian	dot	FALSE
[.data.table	drop	simple	TRUE
[.data.table	on	simple	FALSE
[.data.table	env	abbrev	FALSE
fread	input	simple	FALSE
fread	file	simple	TRUE
fread	text	simple	TRUE
fread	cmd	abbrev	FALSE
fread	sep	abbrev	TRUE
fread	sep2	abbrev	FALSE
fread	dec	abbrev	TRUE
fread	quote	simple	TRUE
fread	nrows	minimal	TRUE
fread	header	simple	TRUE
fread	na.strings	dot	TRUE
fread	stringsAsFactors	camel	TRUE
fread	verbose	simple	FALSE
fread	skip	simple	TRUE
fread	select	simple	FALSE
fread	drop	simple	FALSE
fread	colClasses	camel	TRUE
fread	integer64	minimal	FALSE
fread	col.names	dot	TRUE
fread	check.names	dot	TRUE
fread	encoding	simple	TRUE
fread	strip.white	dot	TRUE
fread	fill	simple	TRUE
fread	blank.lines.skip	dot	TRUE
fread	key	simple	FALSE
fread	index	simple	FALSE
fread	showProgress	camel	FALSE
fread	data.table	dot	FALSE
fread	nThread	camel	FALSE
fread	logical01	simple	FALSE
fread	keepLeadingZeros	camel	FALSE
fread	yaml	acronym	FALSE
fread	autostart	minimal	FALSE
fread	tmpdir	abbrev,minimal	FALSE
fread	tz	acronym	FALSE
fwrite	x	simple	TRUE
fwrite	file	simple	TRUE
fwrite	append	simple	TRUE
fwrite	quote	simple	TRUE
fwrite	sep	abbrev	TRUE
fwrite	sep2	abbrev	FALSE
fwrite	eol	acronym	TRUE
fwrite	na	acronym	TRUE
fwrite	dec	abbrev	TRUE
fwrite	row.names	dot	TRUE
fwrite	col.names	dot	TRUE
fwrite	qmethod	abbrev,minimal	TRUE
fwrite	logical01	minimal	FALSE
fwrite	logicalAsInt	camel	FALSE
fwrite	scipen	abbrev,minimal	FALSE
fwrite	dateTimeAs	camel	FALSE
fwrite	buffMB	abbrev,minimal	FALSE
fwrite	nThread	abbrev,camel	FALSE
fwrite	showProgress	camel	FALSE
fwrite	compress	simple	FALSE
fwrite	yaml	acronym	FALSE
fwrite	bom	acronym	FALSE
fwrite	verbose	simple	FALSE
fwrite	encoding	simple	FALSE")
